# Test the .env creation section
$ownerId = ""
$botPrefix = "!"
$dbHost = "localhost"
$dbUser = "sulfur_bot_user"
$dbPass = "password"
$dbName = "sulfur_bot"
$discordToken = "test_token"
$geminiKey = "test_key"
$openaiKey = "test_key2"

$envContent = @"
# ============================================================
# Sulfur Discord Bot - Configuration
# Generated by Installation Wizard
# ============================================================

# Discord Bot Token
DISCORD_BOT_TOKEN="$discordToken"

# AI API Keys
GEMINI_API_KEY="$geminiKey"
OPENAI_API_KEY="$openaiKey"

# Database Configuration
DB_HOST=$dbHost
DB_USER=$dbUser
DB_PASS=$dbPass
DB_NAME=$dbName

# Bot Settings
BOT_PREFIX=$botPrefix
$(if (![string]::IsNullOrWhiteSpace($ownerId)) { "OWNER_ID=$ownerId" } else { "# OWNER_ID=" })

# Advanced Settings (optional)
# LOG_LEVEL=INFO
# WEB_DASHBOARD_PORT=5000
# DB_POOL_SIZE=5
"@

Write-Host "Environment content created successfully"
Write-Host "Length: $($envContent.Length)"

# Now try the next section
$dbExists = $false
try {
    $testScript = @"
import mysql.connector
"@
    Write-Host "Second here-string created successfully"
} catch {
    Write-Host "Error in second here-string"
}
